name: Notify Discord on PR Open

on:
  pull_request:
    types: [opened, reopened]

jobs:
  send-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_USER: ${{ github.actor }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"📢 New PR opened by \`${PR_USER}\`: **[${PR_TITLE}](${PR_URL})**\"}" \
               $DISCORD_WEBHOOK
