name: Notify Discord on PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            📢 New PR opened by `${{ github.actor }}`: **[${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})**
